name: Infrastructure deployment

on:
  push:
    branches: [main]
    paths:
      - infra/**
      - funcs/**
      - .github/workflows/infra-deploy.yml
  workflow_dispatch:

defaults:
  run:
    working-directory: ./infra

permissions: {}

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest

    environment: prod
    permissions:
      contents: read # To check out code
      id-token: write # To communicate with AWS for credentials

    concurrency:
      group: infra-deploy
      cancel-in-progress: true

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::685873929017:role/statistician-github-actions
          aws-region: us-east-1

      - name: Get AWS SSM parameters
        uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: |
            /statistician/prod/gatekeeper/issuer-url = TF_VAR_gatekeeper_issuer_url,
            /statistician/prod/gatekeeper/client-id = TF_VAR_gatekeeper_statistician_client_id,
            /statistician/prod/tags = TF_VAR_tags

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.15.8"

      - name: Initialize Terraform
        run: terraform init

      - name: Validate infrastructure files
        run: terraform validate -no-color

      # Building is necessary for the planning step to succeed due to how Terraform runs things.
      - name: Build Lambda packages
        run: ../scripts/build_lambdas.sh

      - name: Generate plan
        run: terraform plan -no-color -out=tfplan

      - name: Apply plan
        run: terraform apply -no-color -auto-approve tfplan
